name: FE-CI/CD

# trigger manually
on: workflow_dispatch

# Triggered when code is pushed to any branch in a repository
# on: push
# For more info: https://docs.github.com/en/actions/reference/events-that-trigger-workflows

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    
    # Clone github repo
    - name: Clone FE repository
      uses: actions/checkout@v2
      with:
        repository: lcko1012/travel-blog
        # select branch, default is master          
        ref: 'backup'
    
    # Install NodeJS
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    # Install Dependencies
    - name: Install Dependencies
      run: npm ci
    
    # Build ReactJS
    - name: Build production code
      run: npm run build
      env:
        CI: false
    
    # Share artifact inside workflow
    - name: Share artifact inside workflow
      uses: actions/upload-artifact@v1
      with:
        name: react-build-file
        path: build
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    
      # Download previously shared build
      - name: Get build file
        uses: actions/download-artifact@v1
        with:
          name: react-build-file
          
      # SCP to VPS
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "react-build-file/*"
          target: "/home/ubuntu/"
      
      # Execute Remote Command
      - name: Restart Nginx and clean resources
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            sudo systemctl stop nginx
            sudo cp -ar /home/ubuntu/react-build-file/* /var/www/langthang/
            sudo systemctl start nginx
            sudo rm -rf /home/ubuntu/react-build-file
